# permissions for end users to view clustertypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustertype-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kalypso-scheduler
    app.kubernetes.io/part-of: kalypso-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: clustertype-viewer-role
rules:
- apiGroups:
  - kalypso.kalypso.io
  resources:
  - clustertypes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kalypso.kalypso.io
  resources:
  - clustertypes/status
  verbs:
  - get
