# permissions for end users to edit schedulingpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: schedulingpolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kalypso-scheduler
    app.kubernetes.io/part-of: kalypso-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: schedulingpolicy-editor-role
rules:
- apiGroups:
  - kalypso.kalypso.io
  resources:
  - schedulingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kalypso.kalypso.io
  resources:
  - schedulingpolicies/status
  verbs:
  - get
